title: 'Chris Loewer Blog'
default_lang: en
author:
  name: 'Chris Loewer'
  email: joe@test.com
taxonomies:
  - category
  - tag
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
